auth-service:
  build: ./auth-service
  ports:
    - "3010:8080"
  volumes:
    - ./auth-service:/go/src/github.com/eoengineer/auth-service
translation-service:
  build: ./translation-service
  ports:
    - "3020:8080"
  volumes:
    - ./translation-service:/go/src/github.com/eoengineer/translation-service
